### ISSUE TITLE
m2 macos

### ISSUE THREAD

**Issue by mambo06** [yandex-research/rtdl-revisiting-models#47]
I want to share my recent configuration that works with MacBook with Apple m2 silicon with Sonoma 14.4.
The requirements require modification on data.py line 30:
from :
            subsample=1e9,
to : 
            subsample=int(1e9),

in short :
python == 3.8
libzero==0.0.3.dev7
tensorboard==2.4.1

Other than the 3 above, everything is the default version from pip. Many of the packages supplied in the original requirements are not available or failed to build.

Package lightgbm need to be installed with homebrew:
brew install lightgbm  
 
i can't say the results will be similar since it m2 has mps not cuda.
but i can say for sure m2 is faster compared to i7-12. 

[requirements.txt](https://github.com/yandex-research/rtdl-revisiting-models/files/14955104/requirements.txt)

**Comment by Yura52** [comment]
Many thanks for sharing! I am going to close the issue, but it will remain discoverable in the "closed issues" list. Does this sound good?

**Comment by mambo06** [comment]
thank you
